services:
  db:
    image: postgres:14
    container_name: sp500-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sp500-net

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: sp500-app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - sp500-net
    command: python app.py

volumes:
  pgdata:

networks:
  sp500-net: